# https://docs.astral.sh/uv/guides/integration/docker/#available-images
FROM ghcr.io/astral-sh/uv:python3.13-alpine

# Needed to properly handle UTF-8
ENV PYTHONIOENCODING=UTF-8
ENV LANG=en_US.UTF-8

WORKDIR /

RUN apk update \
    && apk add --no-cache \
    util-linux \
    sudo

COPY requirements-lite.txt /
ARG PACKAGE_VERSION=latest
RUN uv venv --seed && uv pip install --no-cache-dir -r requirements-lite.txt && \
    uv pip install --no-cache-dir pytest-prairielearn-grader==${PACKAGE_VERSION}

# Create 'ag' user for privilege dropping in student code sandbox
RUN adduser -D ag
COPY --chmod=755 run.sh /run.sh

# Add serverFilesCourse to Python path
ENV PYTHONPATH=/grade/serverFilesCourse/

ENTRYPOINT [ "/run.sh" ]
